spring:
  application:
    name: petclinic

server:
  port: 8081
  servlet:
    context-path: /${spring.application.name}
  tomcat:
    accesslog:
      enabled: false
      directory: /var/log/spring/petclinic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/servicediscoverer/eureka/